name: "Mike Roberts Lab @ DSon"
description: "This is the official web page for the Mike Roberts Lab at Dson."

url: ""

paginate: 5
paginate_path: "news/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
